from LinkedList.LinkedList import DoublyLinkedList 
doubly = DoublyLinkedList()
doubly.push(10)
doubly.push(20)
doubly.push(30)
doubly.show()
doubly.pop()
doubly.show()
doubly.pop()
doubly.show()
doubly.pop()
doubly.show()
